name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: npm install
      run: npm install
    - name: npm test
      run: npm test
